spring:
      datasource:
            url: jdbc:mysql://localhost:3306/restaurant
            username: root
            password: 1234
      jpa:
            hibernate:
                  ddl-auto: update
            show-sql: true

server:
      port: 8083